Revert changes to call Looper.prepare() through JNI.
NDK `ALooper_prepare()` was not enough and causing:

> java.lang.RuntimeException: Can't create handler inside thread Thread[Binder:5898_2,5,main] that has not called Looper.prepare()