attempt to fix missing debug.keystore issue.
from https://github.com/atsushieno/aap-juce-obxd/actions/runs/7825155928/job/21348909405
```
if [ ! -f /home/runner/.android/debug.keystore ] ; then \
	keytool -genkey -v -keystore /home/runner/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 37564 -noprompt -dname "CN=Android Debug,O=Android,C=US" ; \
fi
Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 37,564 days
	for: CN=Android Debug, O=Android, C=US
[Storing /home/runner/.android/debug.keystore]
keytool error: java.io.FileNotFoundException: /home/runner/.android/debug.keystore (No such file or directory)
java.io.FileNotFoundException: /home/runner/.android/debug.keystore (No such file or directory)
```